#include "Lexicon.hpp"

using namespace std;

// ---------- ASSEMBLY KEYWORDS ----------

unordered_map <string, BYTE> Parser::assemblyKeyword =
{
    {"NOP",     0x90},
    {"INT3",    0xCC},
    {"PUSHAD",  0x60},
    {"POPAD",   0x61},
};

// ---------- SECTION KEYWORDS ----------

unordered_map <string, DWORD> Parser::sectionKeywords =
{
    // -- WHAT CONTAINS --
    {"CODE",                0x00000020},
    {"INITIALIZED_DATA",    0x00000040},
    {"UNINITIALIZED_DATA",  0x00000080},
    // -- PERMITS --
    {"DISCARDABLE",         0x02000000},
    {"NOT_CACHEABLE",       0x04000000},
    {"NOT_PAGEABLE",        0x08000000},
    {"SHAREADBLE",          0x10000000},
    {"EXECUTABLE",          0x20000000},
    {"READABLE",            0x40000000},
    {"WRITABLE",            0x80000000},
};

// ---------- GENERAL KEYWORDS ----------

unordered_map <string, Parser::FuncParse> Parser::generalKeywords =
{
    // -- CONTAINERS --
    {"SECTION",     {ParseSection,      NULL} },
    {"SEGMENT",     {ParseSegment,      NULL} },
    {"PROC",        {ParseProcedure,    NULL} },
    {"DECLARATION", {ParseDeclaration,  NULL} },

    // -- THUNK --
    {"THUNK",       {ParseThunk,        NULL} },

    // -- OPERATION --
    {"MERGE",       {ParseMerge,        NULL} },

    // -- VARIABLES --
    //FLOATS
    {"REAL10",  {ParseVariable, FuncArgs(10, FPU, NOT_APPLICABLE) } },
    {"REAL8",   {ParseVariable, FuncArgs( 8, FPU, NOT_APPLICABLE) } },
    {"REAL4",   {ParseVariable, FuncArgs( 4, FPU, NOT_APPLICABLE) } },
    //INTEGERS
 // {"OWORD",   {ParseVariable, FuncArgs(16, CPU, UNSIGNED) } },
    {"TBYTE",   {ParseVariable, FuncArgs(10, CPU, UNSIGNED) } },
    {"QWORD",   {ParseVariable, FuncArgs( 8, CPU, UNSIGNED) } },
    {"FWORD",   {ParseVariable, FuncArgs( 6, CPU, UNSIGNED) } },
    {"DWORD",   {ParseVariable, FuncArgs{ 4, CPU, UNSIGNED} } },
    {"WORD",    {ParseVariable, FuncArgs( 2, CPU, UNSIGNED) } },
    {"BYTE",    {ParseVariable, FuncArgs( 1, CPU, UNSIGNED) } },
    //SIGNED
 // {"SOWORD",  {ParseVariable, FuncArgs(16, CPU, SIGNED) } },
    {"STBYTE",  {ParseVariable, FuncArgs(10, CPU, SIGNED) } },
    {"SQWORD",  {ParseVariable, FuncArgs( 8, CPU, SIGNED) } },
    {"SFWORD",  {ParseVariable, FuncArgs( 6, CPU, SIGNED) } },
    {"SDWORD",  {ParseVariable, FuncArgs( 4, CPU, SIGNED) } },
    {"SWORD",   {ParseVariable, FuncArgs( 2, CPU, SIGNED) } },
    {"SBYTE",   {ParseVariable, FuncArgs( 1, CPU, SIGNED) } },
    //ADDITIONAL
    {"TEXT",    {ParseVariable, NULL} },
    //OWN
    {"VAR",     {ParseOwnVar,   NULL} },
};

// ---------- ASSEMBLY DECLARATIONS ----------

unordered_set <string> assemblyDeclarations =
{
    // -- SHORT VARIABLE DECLARATIONS --
    {"DB"},
    {"DW"},
    {"DD"},
    {"DF"},
    {"DQ"},
    {"DO"},
    // -- LONG VARIABLE DECLARATIONS --
    // UNSIGNED
    {"BYTE"},
    {"WORD"},
    {"DWORD"},
    {"FWORD"},
    {"QWORD"},
    {"OWORD"},
    // SIGNED
    {"SBYTE"},
    {"SWORD"},
    {"SDWORD"},
    {"SFWORD"},
    {"SQWORD"},
    {"SOWORD"},
    // FLOAT
    {"REAL4"},
    {"REAL8"},
    {"REAL10"},
    // -- OTHER DECLARATIONS --
    {"PROC"},
    {"STRUCT"},
    {"MACRO"},
    {"LABEL"},

};

// ---------- ASSEMBLY COMMANDS ----------

unordered_set <string> assemblyCommands =
{
    // -- FLAGS --
    {"CLC"},
    {"CLD"},
    {"CLI"},
    {"STC"},
    {"STD"},
    {"STI"},
    // -- INTERRUPT --
    {"INT"},
    {"INTO"},
    {"INT1"},
    {"INT3"},
    {"INT01"},
    {"INT03"},
    {"HLT"},
    {"WAIT"},
    // -- SYSTEM --
    {"SYSCALL"},
    {"SYSENTER"},
    {"SYSEXIT"},
    {"SYSRET"},
    // -- PORT --
    {"IN"},
    {"INS"},
    {"INSB"},
    {"INSW"},
    {"INSD"},
    {"OUT"},
    {"OUTS"},
    {"OUTSB"},
    {"OUTSW"},
    {"OUTSD"},
    // -- STACK --
    {"PUSH"},
    {"POP"},
    {"PUSHF"},
    {"POPF"},
    {"PUSHA"},
    {"POPA"},
    {"PUSHW"},
    {"PUSHD"},
    {"PUSHAD"},
    {"POPAD"},
    {"PUSHFD"},
    {"POPFD"},
    {"PUSHAW"},
    {"POPAW"},
    {"PUSHFW"},
    {"POPFW"},
    {"ENTER"},
    {"LEAVE"},
    // -- JUMPS --
    {"JMP"},
    {"CALL"},
    {"RET"},
    {"RETF"},
    {"IRET"},
    {"IRETW"},
    {"IRETF"},
    {"IRETD"},
    {"IRETDF"},
    {"RETN"},
    // -- CONDITIONAL JUMPS --
    {"JC"},
    {"JS"},
    {"JZ"},
    {"JE"},
    {"JA"},
    {"JB"},
    {"JG"},
    {"JL"},
    {"JO"},
    {"JP"},
    {"JPE"},
    {"JAE"},
    {"JBE"},
    {"JGE"},
    {"JLE"},
    {"JCXZ"},
    {"JECXZ"},
    // -- NEGATED CONDITIONAL JUMPS --
    {"JNC"},
    {"JNS"},
    {"JNZ"},
    {"JNE"},
    {"JNA"},
    {"JNB"},
    {"JNG"},
    {"JNL"},
    {"JNO"},
    {"JNP"},
    {"JNPE"},
    {"JNAE"},
    {"JNBE"},
    {"JNGE"},
    {"JNLE"},
    // -- LOOP --
    {"LOOP"},
    {"LOOPE"},
    {"LOOPEW"},
    {"LOOPNE"},
    {"LOOPNEW"},
    {"LOOPNZ"},
    {"LOOPNZW"},
    {"LOOPW"},
    {"LOOPZ"},
    {"LOOPZW"},
    {"LOOPD"},
    {"LOOPED"},
    {"LOOPNED"},
    {"LOOPNZD"},
    {"LOOPZD"},
    {"REP"},
    {"REPE"},
    {"REPNE"},
    {"REPNZ"},
    {"REPZ"},
    // -- CPU - COMPARISON --
    {"CMP"},
    {"CMPS"},
    {"CMPSB"},
    {"CMPSW"},
    {"CMPSD"},
    {"CMPXCHG"},
    {"CMPXCHG486"},
    {"CMPXCHG8B"},
    {"SCAS"},
    {"SCASB"},
    {"SCASW"},
    {"SCASD"},
    // -- CPU - TRANSFER --
    {"LDS"},
    {"LES"},
    {"LODS"},
    {"LODSB"},
    {"LODSW"},
    {"LODSD"},
    {"STOS"},
    {"STOSB"},
    {"STOSW"},
    {"STOSD"},
    {"MOV"},
    {"UMOV"},
    {"MOVABS"},
    {"MOVZX"},
    {"MOVS"},
    {"MOVSB"},
    {"MOVSW"},
    {"MOVSD"},
    {"MOVSX"},
    {"MOVSXD"},
    // -- CPU - CONDITIONAL TRANSFER --
    {"CMOVO"},
    {"CMOVNO"},
    {"CMOVB"},
    {"CMOVC"},
    {"CMOVNAE"},
    {"CMOVAE"},
    {"CMOVNB"},
    {"CMOVNC"},
    {"CMOVE"},
    {"CMOVZ"},
    {"CMOVNE"},
    {"CMOVNZ"},
    {"CMOVBE"},
    {"CMOVNA"},
    {"CMOVA"},
    {"CMOVNBE"},
    {"CMOVS"},
    {"CMOVNS"},
    {"CMOVP"},
    {"CMOVPE"},
    {"CMOVNP"},
    {"CMOVPO"},
    {"CMOVL"},
    {"CMOVNGE"},
    {"CMOVGE"},
    {"CMOVNL"},
    {"CMOVLE"},
    {"CMOVNG"},
    {"CMOVG"},
    {"CMOVNLE"},
    // -- SET --
    {"SETA"},
    {"SETAE"},
    {"SETB"},
    {"SETBE"},
    {"SETC"},
    {"SETE"},
    {"SETG"},
    {"SETGE"},
    {"SETL"},
    {"SETLE"},
    {"SETNA"},
    {"SETNAE"},
    {"SETNB"},
    {"SETNBE"},
    {"SETNC"},
    {"SETNE"},
    {"SETNG"},
    {"SETNGE"},
    {"SETNL"},
    {"SETNLE"},
    {"SETNO"},
    {"SETNP"},
    {"SETNS"},
    {"SETNZ"},
    {"SETO"},
    {"SETP"},
    {"SETPE"},
    {"SETPO"},
    {"SETS"},
    {"SETZ"},
    // -- CPU - ARITHMETIC --
    {"ADD"},
    {"ADC"},
    {"XADD"},
    {"SUB"},
    {"SBB"},
    {"MUL"},
    {"IMUL"},
    {"DIV"},
    {"IDIV"},
    {"INC"},
    {"DEC"},
    {"NEG"},
    // -- CPU - BIT --
    {"TEST"},
    {"AND"},
    {"OR"},
    {"XOR"},
    {"NOT"},
    {"BSF"},
    {"BSR"},
    {"BT"},
    {"BTC"},
    {"BTR"},
    {"BTS"},
    // -- CPU - BIT SHIFT --
    {"RCL"},
    {"RCR"},
    {"ROL"},
    {"ROR"},
    {"SAL"},
    {"SAR"},
    {"SHL"},
    {"SHR"},
    {"SHLD"},
    {"SHRD"},
    // -- CPU - CONVERT --
    {"CBW"},
    {"CWD"},
    {"CDQ"},
    {"CWDE"},
    {"CDQE"},
    // -- CPU - RANDOM --
    {"RDRAND"},
    {"RDSEED"},
    // -- CPU - REST --
    {"NOP"},
    {"AAA"},
    {"AAD"},
    {"AAM"},
    {"AAS"},
    {"CMC"},
    {"DAA"},
    {"DAS"},
    {"ESC"},
    {"LEA"},
    {"LAHF"},
    {"SAHF"},
    {"XCHG"},
    {"BSWAP"},
    {"XLAT"},
    {"XLATB"},
    {"BOUND"},
    {"ARPL"},
    {"LAR"},
    {"LSL"},
    {"SGDT"},
    {"SIDT"},
    {"SLDT"},
    {"SMSW"},
    {"STR"},
    {"VERR"},
    {"VERW"},
    {"CLTS"},
    {"LGDT"},
    {"LIDT"},
    {"LLDT"},
    {"LMSW"},
    {"LTR"},
    {"LFS"},
    {"LGS"},
    {"LSS"},
    {"INVD"},
    {"INVLPG"},
    {"WBINVD"},
    {"LOCK"},
    {"CFLUSH"},
    {"CPUID"},
    {"EMMS"},
    {"FEMMS"},
    {"LOADALL"},
    {"LOADALL286"},
    {"IBTS"},
    {"ICEBP"},
    {"RDMSR"},
    {"RDPMC"},
    {"RDSHR"},
    {"RDTSC"},
    {"RSDC"},
    {"RSLDT"},
    {"RSM"},
    {"RSTS"},
    {"SALC"},
    {"SMI"},
    {"SMINT"},
    {"SMINTOLD"},
    {"SVDC"},
    {"SVLDT"},
    {"SVTS"},
    {"UD0"},
    {"UD1"},
    {"UD2"},
    {"XBTS"},
    {"WRMSR"},
    {"WRSHR"},
    // -- FPU - FLOATING --
    {"FLD"},
    {"FST"},
    {"FSTP"},
    {"FADD"},
    {"FADDP"},
    {"FSUB"},
    {"FSUBR"},
    {"FSUBRP"},
    {"FMUL"},
    {"FDIV"},
    {"FDIVR"},
    {"FDIVRP"},
    // -- FPU - INTEGER --
    {"FILD"},
    {"FIST"},
    {"FISTP"},
    {"FIADD"},
    {"FIADDP"},
    {"FISUB"},
    {"FISUBR"},
    {"FISUBRP"},
    {"FIMUL"},
    {"FIDIV"},
    {"FIDIVR"},
    {"FIDIVRP"},
    {"FICOM"},
    {"FICOMP"},
    // -- FPU - REST --
    {"FABS"},
    {"FXCH"},
};

// ---------- ASSEMBLY KEYWORDS TO AVOID ----------

unordered_set <string> keywordsToAvoidByConverter =
{
    {"COMMENT"},
    {"INCLUDELIB"},
    {"INCLUDE"},
    {"EQU"},
    {"DEFINE"},
    {"EXTERNDEF"},
    {"OPTION"},
    {"ASSUME"},
    {"MACRO"},
    {"ENDM"},
    {"IFDEF"},
    {"IFNDEF"},

    {"TEXT"},
};

// ---------- REGISTERS ----------

unordered_set <string> asmRegisters =
{
    //64-bit
    {"RAX"},
    {"RBX"},
    {"RCX"},
    {"RDX"},
    {"RSI"},
    {"RDI"},
    {"RBP"},
    {"RSP"},
    //32-bit
    {"EAX"},
    {"EBX"},
    {"ECX"},
    {"EDX"},
    {"ESI"},
    {"EDI"},
    {"EBP"},
    {"ESP"},
    //16-bit,
    {"AX"},
    {"BX"},
    {"CX"},
    {"DX"},
    {"SI"},
    {"DI"},
    {"BP"},
    {"SP"},
    //8-bit,
    {"AL"},
    {"BL"},
    {"CL"},
    {"DL"},
    {"AH"},
    {"BH"},
    {"CH"},
    {"DH"},
    //segment
    {"CS"},
    {"DS"},
    {"ES"},
    {"SS"},
    {"FS"},
    {"GS"},
};

